### PR TITLE
Feature edit course attributes

### PR DESCRIPTION
**Pull request by wallerb7039**
Functionality and tests complete. Does NOT include tests for getting course attributes, though functions are there. May go back and refactor for security reasons, but does work as is.

### CODE REVIEW

**Review by EndureBlackout — APPROVED** [review]

**Comment by EndureBlackout** [comment]
Only comment is (I know you addressed this in your comment) that we should be using prepared statements obviously for security reasons.

**Comment by MattFriemoth** [comment]
I think that this function should use the predefined SQL tools. Could you refactor it to use the functions within the sqltools.js file? There are a few examples from the Users file.
Also, there are tests present for the delete endpoint, it wouldn't have gotten push to staging if it had not, there is no reason to comment it out.

**Comment by wallerb7039** [comment]
Refactored to be more secure via functions in sqltools.js. Also was able to get deleteCourse back in with its respective tests. Had to rename 'courseId' to 'section' because the sqltools.js function wouldn't account for extra quotation marks and didn't want to change it as it is being used by other files.

**Comment by wallerb7039** [comment]
Should be good to go with merging in Brandon's search tests, but wouldn't hurt to look back over them to make sure I didn't accidentally forget/add in something when I was fixing conflicts.

**Review by vandonfx — APPROVED** [review]

**Pull request merged**
