### PR TITLE
Fix permission checking

### PR DESCRIPTION
**Pull request by EndureBlackout**

### CODE REVIEW

**Comment by EndureBlackout** [comment]
The amount removed is scaring me...

**Comment by EndureBlackout** [comment]
> 

Seems fine though. Just tested the endpoints on my local machine.

**Comment by wallerb7039** [comment]
I was just gonna as if the package-lock.json on your local machine the same as the absolutely upside down one in the PR or is it normal?

**Comment by EndureBlackout** [comment]
> I was just gonna ask if the package-lock.json on your local machine is the same as the absolutely upside down one in the PR or is it normal?

Woah idk what is going on there... one sec.

**Comment by EndureBlackout** [comment]
@wallerb7039 That looks better :)

**Review by wallerb7039 — APPROVED** [review]

**Review by Eneuwi — APPROVED** [review]

**Pull request merged**
